### PR TITLE
Move some messages to debugging. Add action variable.

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Comment by djMax** [comment]
Thanks for this! One bug I'm seeing but haven't had time to dig into is that after some time, HomeKit just stops talking to the server. As if it hasn't heard back on something and will not continue until it does. I was going to add some callback-watchdog-timers to see, but it's very odd...

**Comment by dsully** [comment]
Is that generic to HomeBridge, or specific to the RRA2 plugin?

**Comment by djMax** [comment]
It's unclear because this is pretty much all I use (RRA2) - I have Nest and Sonos but I think it has something to do with the number of lights. The Home app starts on the page that has all the favorites, so it means I get a boat load of queries all at once. I'm hoping it's a bug in this rra2 code and not HomeBridge or HomeKit itself...

**Comment by dsully** [comment]
I've not gone through the code in detail (JS isn't a native language for me), but it looked like you were keeping a cache? Is that monitoring the light states as ~OUTPUTs are received from the controller?

**Comment by djMax** [comment]
Yes.

**Comment by djMax** [comment]
The JS side I can handle, but it's unclear what HomeKit is expecting behavior-wise (for example, when someone sets the brightness to 0, I want to tell the system that the "power" is now off too, but it's unclear how to do that, so I do hokey things to try and make it work)

**Pull request merged**
